name: Buildozer Android

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build on Android
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Buildozer and Android dependencies
        uses: actions/cache@v4
        id: cache-buildozer
        with:
          path: |
            .buildozer
            ~/.buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}

      - name: Install dependencies
        if: steps.cache-buildozer.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libgdbm-dev libssl-dev libffi-dev libsqlite3-dev libbz2-dev libreadline-dev libjpeg-dev libfreetype6-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libgles2-mesa-dev
          pip install --upgrade pip
          pip install "setuptools<68.0.0"
          pip install cython==0.29.34 buildozer

      - name: Accept Android Licenses
        if: steps.cache-buildozer.outputs.cache-hit != 'true'
        run: |
          yes | buildozer android update

      - name: Build and deploy
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: bin/*.apk
