name: Buildozer Android

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build on Android
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: kivy/build-on-android-action@v1.2.0
        with:
          # Dodaj tutaj swoje komendy buildozera
          command: 'buildozer android debug'
